In [1]:
import numpy as np

my_data = np.genfromtxt("data.txt",delimiter =",")
my_data = my_data.astype("int32")
my_data

array([[  2,   5,  36,   2,   8],
       [ 55,   6,  97,   4, 256],
       [245,   4,  32, 258,  65],
       [134, 345, 652, 945, 121]], dtype=int32)

In [3]:
bool_data=my_data>100
bool_data

array([[False, False, False, False, False],
       [False, False, False, False,  True],
       [ True, False, False,  True, False],
       [ True,  True,  True,  True,  True]])

In [4]:
my_data[bool_data]

array([256, 245, 258, 134, 345, 652, 945, 121], dtype=int32)

In [5]:
in_50_100 = (my_data > 50) & (my_data < 100)
in_50_100

array([[False, False, False, False, False],
       [ True, False,  True, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False]])

In [10]:
not_in_50_100 = ~((my_data > 50) & (my_data < 100))
not_in_50_100

array([[ True,  True,  True,  True,  True],
       [False,  True, False,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True]])

In [ ]:
any_gt_100_by_row = np.any(my_data>100, axis=1)