In [2]:
import numpy as np

vecteur_1d = np.array([1,2,3,4,5,6,7,8,9,10])

In [3]:
vecteur_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
vecteur_1d[1]

2

In [5]:
vecteur_1d[[1,3]]

array([2, 4])

In [6]:
vecteur_1d[[0,-1]]

array([ 1, 10])

In [7]:
vecteur_1d[2:6]

array([3, 4, 5, 6])

In [8]:
vecteur_1d[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
vecteur_1d[0:10:2]

array([1, 3, 5, 7, 9])

In [21]:
vecteur_2d = np.array([[1,2,3],
                       [4,5,6],
                       [7,8,9],
                       [10,11,12],
                       [13,14,15]])
vecteur_2d


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [11]:
vecteur_2d[0,0]

1

In [12]:
vecteur_2d[1,1]

5

In [13]:
vecteur_2d[2,2]

9

In [14]:
vecteur_2d[:,:]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [15]:
vecteur_2d[1,:]

array([4, 5, 6])

In [16]:
vecteur_2d[:,1]

array([ 2,  5,  8, 11, 14])

In [17]:
vecteur_3d = np.array(
    [[[1,0,0], [0,0,0]],
     [[0,2,0], [0,0,3]]
     ])
vecteur_3d

array([[[1, 0, 0],
        [0, 0, 0]],

       [[0, 2, 0],
        [0, 0, 3]]])

In [18]:
vecteur_3d[0,0,0]

1

In [19]:
vecteur_3d[1,0,1]

2

In [20]:
vecteur_3d[1,1,2]

3