In [24]:
import numpy as np

vecteur_1d = np.array([1,2,3,4,5,6,7,8,9,10])

In [25]:
vecteur_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
vecteur_1d[1]

2

In [27]:
vecteur_1d[[1,3]]

array([2, 4])

In [28]:
vecteur_1d[[0,-1]]

array([ 1, 10])

In [29]:
vecteur_1d[2:6]

array([3, 4, 5, 6])

In [30]:
vecteur_1d[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
vecteur_1d[0:10:2]

array([1, 3, 5, 7, 9])

In [32]:
vecteur_2d = np.array([[1,2,3],
                       [4,5,6],
                       [7,8,9],
                       [10,11,12],
                       [13,14,15]])
vecteur_2d


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [33]:
vecteur_2d[0,0]

1

In [34]:
vecteur_2d[1,1]

5

In [35]:
vecteur_2d[2,2]

9

In [40]:
vecteur_2d[:,:]


array([[999,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [ 10,  11,  12],
       [ 13,  14,  15]])

In [37]:
vecteur_2d[1,:]

array([4, 5, 6])

In [41]:
vecteur_2d[:,1]

array([2, 5])

In [42]:
vecteur_3d = np.array(
    [[[1,0,0], [0,0,0]],
     [[0,2,0], [0,0,3]]
     ])
vecteur_3d

array([[[1, 0, 0],
        [0, 0, 0]],

       [[0, 2, 0],
        [0, 0, 3]]])

In [43]:
vecteur_3d[0,0,0]

1

In [44]:
vecteur_3d[1,0,1]

2

In [45]:
vecteur_3d[1,1,2]

3