In [17]:
import numpy as np

vecteur1 = np.array([1,2,3,4,5])
vecteur1

array([1, 2, 3, 4, 5])

In [18]:
vecteur1+2

array([3, 4, 5, 6, 7])

In [19]:
vecteur1-2

array([-1,  0,  1,  2,  3])

In [20]:
vecteur1*2

array([ 2,  4,  6,  8, 10])

In [21]:
vecteur1/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [22]:
vecteur1**2

array([ 1,  4,  9, 16, 25])

In [23]:
np.cos(vecteur1)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [31]:
import numpy as np
mat1 = np.random.randint(-10,10, size=(3,4))
mat2 = np.random.randint(-10,10, size=(4,2))

# Create a 2x2 matrix
matrix = np.array([[1, 2], [3, 4]])

# Calculate the inverse of the matrix
inverse_matrix = np.linalg.inv(matrix)

print(inverse_matrix)
rounded_matrix = np.round(matrix)

print(np.round(np.matmul(inverse_matrix, matrix)))

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1. 0.]
 [0. 1.]]


In [25]:
mat1

array([[-7,  7,  9,  5],
       [-6, -8,  8,  8],
       [-2,  2, -9,  7]])

In [26]:
mat2

array([[-3, -8],
       [ 9,  9],
       [ 4, -3],
       [ 2, -8]])

In [27]:
np.matmul(mat1,mat2)

array([[ 130,   52],
       [  -6, -112],
       [   2,    5]])