In [27]:
import numpy as np

vecteur1 = np.array([1,2,3,4,5])
vecteur1

array([1, 2, 3, 4, 5])

In [28]:
vecteur1+2

array([3, 4, 5, 6, 7])

In [29]:
vecteur1-2

array([-1,  0,  1,  2,  3])

In [30]:
vecteur1*2

array([ 2,  4,  6,  8, 10])

In [31]:
vecteur1/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [32]:
vecteur1**2

array([ 1,  4,  9, 16, 25])

In [33]:
np.cos(vecteur1)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [34]:
mat1 = np.random.randint(-10,10, size=(3,4))
mat2 = np.random.randint(-10,10, size=(4,2))

In [35]:
mat1

array([[ -3,  -4,   8,   3],
       [-10,   1,   8,   3],
       [  5,   6, -10,  -3]])

In [36]:
mat2

array([[ 1,  5],
       [ 0, -7],
       [ 7, -2],
       [-3,  1]])

In [37]:
np.matmul(mat1,mat2)

array([[ 44,   0],
       [ 37, -70],
       [-56,   0]])