In [10]:
import numpy as np
mat1 = np.array([[1,2,3,4], [5,6,7,8]])
mat1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
mat2 = mat1.reshape(4,2)
mat2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [12]:
mat3 = mat1.reshape(2,2,2)
mat3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [13]:
mat4 = mat1.reshape(2,20)
mat4

ValueError: cannot reshape array of size 8 into shape (2,20)

In [15]:
vec1 = np.array([1,2,3,4,5])
vec2 = np.array([6,7,8,9,10])

In [19]:
v_stack_vec = np.vstack([vec1,vec2])
v_stack_vec

TypeError: vstack() takes 1 positional argument but 2 were given

In [18]:
v_stack_big_vec = np.vstack([vec1,vec2,vec1,vec2])
v_stack_big_vec

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [20]:
h_stack_vec = np.hstack([vec1,vec2])
h_stack_vec

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])