In [43]:
import numpy as np



In [44]:
mat1 = np.random.randint(-10,10, size=(5,5))
mat1

array([[  3,   8,  -6,  -6,   2],
       [ -8,  -7,   0,  -2,  -3],
       [  7,   6,   3,  -3,  -6],
       [  9,  -5, -10,   9,  -7],
       [  3,   9,   3,   5,  -4]])

In [45]:
np.min(mat1)

-10

In [46]:
np.max(mat1)

9

In [47]:
np.min(mat1, axis=0) #Par colonne

array([ -8,  -7, -10,  -6,  -7])

In [53]:
np.min(mat1, axis=1) #Par ligne

array([ -6,  -8,  -6, -10,  -4])

In [49]:
np.mean(mat1, axis=0) #Moyenne par colonne

array([ 2.8,  2.2, -2. ,  0.6, -3.6])

In [50]:
np.std(mat1, axis=0) #Ecart-type par colonne

array([5.87877538, 6.7941151 , 5.17687164, 5.535341  , 3.13687743])

In [52]:
np.sum(mat1, axis=1) #Sommes par ligne

array([  1, -20,   7,  -4,  16])