In [1]:
import numpy as np



In [2]:
mat1 = np.random.randint(-10,10, size=(5,5))
mat1

array([[ -2,   7,  -1,  -9,   1],
       [ -7,   3,  -7,   7,   9],
       [  9,  -9, -10,  -6,  -2],
       [  5,   5,   7,  -7,   2],
       [ -1,  -7,  -3,   7,   6]])

In [10]:
np.min(mat1)
np.linalg.eigvals(mat1)

array([-14.12373168+0.j        ,  -2.72157273+9.17553161j,
        -2.72157273-9.17553161j,   4.78343857+6.15124058j,
         4.78343857-6.15124058j])

In [4]:
np.max(mat1)

9

In [5]:
np.min(mat1, axis=0) #Par colonne

array([ -7,  -9, -10,  -9,  -2])

In [6]:
np.min(mat1, axis=1) #Par ligne

array([ -9,  -7, -10,  -7,  -7])

In [7]:
np.mean(mat1, axis=0) #Moyenne par colonne

array([ 0.8, -0.2, -2.8, -1.6,  3.2])

In [8]:
np.std(mat1, axis=0) #Ecart-type par colonne

array([5.6       , 6.52380257, 5.81033562, 7.08801806, 3.86781592])

In [9]:
np.sum(mat1, axis=1) #Sommes par ligne

array([ -4,   5, -18,  12,   2])