In [17]:
import numpy as np



In [18]:
mat1 = np.random.randint(-10,10, size=(5,5))
mat1

array([[  5,  -8,  -8,  -9,   3],
       [  2,   6,   6,  -7,  -3],
       [  9,   7,   8,  -8,  -2],
       [ -2,   6,  -9,   6,   6],
       [  1, -10,   1,   3,  -1]])

In [19]:
mat1.min() # ou np.min(mat1)

-10

In [20]:
np.linalg.eigvals(mat1)

array([13.36556322+4.34400005j, 13.36556322-4.34400005j,
       -1.38861682+5.44951955j, -1.38861682-5.44951955j,
        0.0461072 +0.j        ])

In [21]:
mat1.max() # ou np.max(mat1)

9

In [22]:
np.min(mat1, axis=0) #Par colonne

array([ -2, -10,  -9,  -9,  -3])

In [23]:
np.min(mat1, axis=1) #Par ligne

array([ -9,  -7,  -8,  -9, -10])

In [24]:
np.mean(mat1, axis=0) #Moyenne par colonne

array([ 3. ,  0.2, -0.4, -3. ,  0.6])

In [25]:
np.std(mat1, axis=0) #Ecart-type par colonne

array([3.74165739, 7.54718491, 7.00285656, 6.2289646 , 3.38230691])

In [26]:
np.sum(mat1, axis=1) #Sommes par ligne

array([-17,   4,  14,   7,  -6])

In [29]:
M = np.matrix([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
v = np.array([1,2,3])

In [30]:
M.dot(v) # to multiply a matrix by a vector

matrix([[14, 32, 50]])

In [32]:
M = np.matrix([
    [2,-1,0],
    [-1,2,-1],
    [0,-1,2]
])
np.linalg.inv(M)