In [1]:
import numpy as np
vecteur1 = np.zeros(10)
print(vecteur1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [2]:
vecteur2 = np.zeros(10,dtype="int32")
print(vecteur2)

[0 0 0 0 0 0 0 0 0 0]


In [4]:
vecteur3 = np.ones((3,4), dtype="int16")
print(vecteur3)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [7]:
vecteur1 = np.full((3,4), 5)
print(vecteur1)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [9]:
vecteur2 = np.full_like(vecteur1, 10)
print(vecteur2)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [13]:
vecteur3 = np.identity(3)
print(vecteur3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
