In [2]:
%pip install -U numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

vecteur = np.array([1,2,3,4])
print(vecteur)

[1 2 3 4]


In [6]:
vecteur_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(vecteur_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
vecteur_3d = np.array(
    [
        [
            [1,1,1],
            [1,1,1]
        ],
        [
            [2,2,2],
            [2,2,2]]])
print(vecteur_3d)

[[[1 1 1]
  [1 1 1]]

 [[2 2 2]
  [2 2 2]]]


In [10]:
vecteur = np.array([1,2,3,4])
print(f"vecteur : {vecteur}")
print(f"nombre de dimensions = {vecteur.ndim}")
print(f"les dimensions sont: {vecteur.shape}")

vecteur : [1 2 3 4]
nombre de dimensions = 1
les dimensions sont: (4,)


In [13]:
vecteur_3d = np.array([[[1,1,1,1], [1,1,1,1], [1,1,1,1]],
                       [[2,2,2,2], [2,2,2,2], [2,2,2,2]]])
print(f"vecteur : \n{vecteur_3d}")
print(f"nombre de dimensions = {vecteur_3d.ndim}")
print(f"les dimensions sont: {vecteur_3d.shape}")

vecteur : 
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]]
nombre de dimensions = 3
les dimensions sont: (2, 3, 4)
